In [1]:
import os
os.chdir('../')
os.getcwd()

'/media/nazirnayal/DATA/projects/attention_long_tail/paying-attention-to-the-long-tail'

In [2]:
%load_ext autoreload
%autoreload 2

In [3]:
import torch
import numpy as np

In [4]:
a = np.array([1, 1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 8])

In [5]:
np.where(np.isin(a, [1, 3, 5]))

(array([ 0,  1,  2,  5,  6,  9, 10]),)

# General Setup

In [30]:
few_shot_classes = [0, 1, 2]
medium_shot_classes = [3, 4, 5]
many_shot_classes = [6, 7, 8]

targets = [0, 0, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5, 6, 6, 6, 7, 7, 7, 8, 8, 8]
output  = [0, 1, 2, 1, 3, 4, 2, 5, 6, 3, 3, 1, 8, 4, 4, 5, 3, 2, 6, 7, 1, 7, 2, 4, 8, 0, 5]

targets = torch.Tensor(targets)
output = torch.Tensor(output)

logits = torch.randn((len(targets), 9))

# Test KShot Accuracy

In [17]:
from metrics.classification import KShotAccuracy

In [29]:
kshot_acc = KShotAccuracy(few_shot_classes, medium_shot_classes, many_shot_classes)

In [31]:
kshot_acc(output, targets)

(tensor(0.3333), tensor(0.5556), tensor(0.3333))

In [32]:
kshot_acc.compute()

(tensor(0.3333), tensor(0.5556), tensor(0.3333))

# Test KShot Precision

In [33]:
from metrics.classification import KShotPrecision

In [31]:
kshot_precision = KShotPrecision(few_shot_classes, medium_shot_classes, many_shot_classes)

NameError: name 'KShotPrecision' is not defined

In [36]:
kshot_precision(output, targets)

(tensor(0.3000), tensor(0.4545), tensor(0.5000))

In [37]:
kshot_precision.compute()

(tensor(0.3000), tensor(0.4545), tensor(0.5000))

# Test KShot F1

In [48]:
from metrics.classification import KShotF1

In [49]:
kshot_f1 = KShotF1(few_shot_classes, medium_shot_classes, many_shot_classes)

In [50]:
kshot_f1(output, targets)

(tensor(0.3158), tensor(0.5000), tensor(0.4000))

In [51]:
kshot_f1.compute()

(tensor(0.3158), tensor(0.5000), tensor(0.4000))

In [52]:
kshot_f1.reset()
kshot_f1.compute()

(tensor(0.3158), tensor(0.5000), tensor(0.4000))

In [53]:
kshot_f1(torch.Tensor([0, 1, 1, 2, 3, 4, 7, 8, 7]), torch.Tensor([1, 1, 0, 2, 2, 2, 7, 7, 7]))

(tensor(0.4000), 0, tensor(0.6667))

In [54]:
kshot_f1.compute()

(tensor(0.4000), 0, tensor(0.6667))

In [56]:
kshot_f1(output, targets)
kshot_f1.compute()

(tensor(0.3158), tensor(0.5000), tensor(0.4000))

In [57]:
kshot_f1.compute()

(tensor(0.3158), tensor(0.5000), tensor(0.4000))

# Test KShot mAP

In [7]:
from metrics.classification import KShotmAP

In [35]:
kshot_map = KShotmAP(few_shot_classes, medium_shot_classes, many_shot_classes)

In [37]:
kshot_map(logits, targets)

(27, 3) (27,)
(27, 3) (27,)


(tensor(0.5191), tensor(0.5309), tensor(0.6317))

In [29]:
targets.unsqueeze(0)

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0.]])

In [68]:
kshot_map.compute()

(tensor(0.4259), tensor(0.4747), tensor(0.4815))

In [69]:
kshot_map.reset()
kshot_map(torch.Tensor([0, 1, 1]), torch.Tensor([1, 1, 0]))

(tensor(1.), tensor(nan), tensor(nan))

# Test Operations

In [73]:
few_index = np.isin(targets, few_shot_classes)

In [78]:
a = np.random.randn(5, 10)

In [80]:
a

array([[ 1.14714590e+00, -1.63413941e-01, -2.02308078e-01,
        -7.64310154e-01, -6.80477724e-02, -1.82405258e-01,
         1.35195412e+00, -1.96038227e-01, -1.27682739e-01,
        -7.52517480e-01],
       [ 4.59570355e-01, -1.74835900e-01, -1.57434719e+00,
        -1.41275337e+00,  7.94968610e-04, -1.65658101e+00,
         2.77241573e-01,  1.52173109e+00,  2.05000875e+00,
        -5.81942996e-01],
       [-1.06757485e+00, -1.78662041e+00, -1.68172430e-01,
        -7.67709644e-01,  7.10804654e-01, -1.05814826e+00,
         1.45614554e+00,  1.61743186e+00,  7.34027045e-01,
        -4.93252534e-01],
       [-9.46190671e-01, -1.35010649e-01,  1.32096434e-01,
         1.48568431e+00, -2.04754632e-01,  6.52498738e-01,
        -1.47752191e+00,  9.46675229e-01, -1.07989556e+00,
        -9.37349248e-01],
       [-1.60863651e+00, -8.99207846e-01,  1.81027686e+00,
        -2.18225722e-01,  2.48246297e-01,  1.06931578e+00,
        -1.63354795e+00,  6.41030229e-01, -3.99618932e-01,
        -1.

In [79]:
k = np.zeros((5, 3))

In [81]:
k[:,0] = np.max(a[:,[0, 1, 2]], axis=1)

In [82]:
k

array([[ 1.1471459 ,  0.        ,  0.        ],
       [ 0.45957035,  0.        ,  0.        ],
       [-0.16817243,  0.        ,  0.        ],
       [ 0.13209643,  0.        ,  0.        ],
       [ 1.81027686,  0.        ,  0.        ]])

In [75]:
a = np.random.randn(3, 3)
b = np.random.randn(3, 3)

In [76]:
x = np.array([a, b])

In [77]:
x_0 = np.array([1, 1])

In [67]:
d = x.dot(x_0)

In [69]:
x

array([[[ 0.37532889, -0.54136463],
        [ 0.53661224, -0.16699857]],

       [[-1.76460228,  0.95153931],
        [-1.09968922, -0.52459038]]])

In [83]:
x_0.reshape((1, 2)).dot(x)

ValueError: shapes (1,2) and (2,3,3) not aligned: 2 (dim 1) != 3 (dim 1)

In [80]:
x_0.T.dot(x)

ValueError: shapes (2,) and (2,3,3) not aligned: 2 (dim 0) != 3 (dim 1)